fail_fast: true
repos:
  - repo: https://github.com/pre-commit/mirrors-eslint
    rev: "v9.1.1"
    hooks:
      - id: eslint
        files: \.[jt]sx?$ # *.js, *.jsx, *.ts and *.tsx
        types: [file]
        additional_dependencies:
          - eslint-plugin-prettier
          - eslint-config-prettier
          - prettier
          - eslint-plugin-react@latest
          - typescript-eslint
  - repo: https://github.com/astral-sh/ruff-pre-commit
    # Ruff version.
    rev: v0.4.2
    hooks:
      # Run the linter.
      - id: ruff
        # Python
        files: \.py$
        types: [file]
      # Run the formatter.
      - id: ruff-format
        files: \.py$
        types: [file]
