services:
  # A Docker web service
  - type: web
    name: langflow
    runtime: docker
    dockerfilePath: ./Dockerfile
    repo: https://github.com/logspace-ai/langflow
    branch: form_io
    healthCheckPath: /health
    autoDeploy: false
